apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: timeapi
spec:
  hostnames:
    - timeapi.kind.local
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: timeapi
      namespace: default
  rules:
    - matches:
        - path:
            type: Exact
            value: /time
      backendRefs:
        - name: timeapi
          port: 8080
          