run:
  timeout: 10m

linters-settings:
  cyclop:    
    max-complexity: 20 # The maximal code complexity to report. # Default: 10.
  lll:
    line-length: 150
  gci:
    sections:
    - standard                                               # Captures all standard packages if they do not match another section.
    - default                                                # Contains all imports that could not be matched to another section type.
    - prefix(github.com/cheina97/timeserver)  # Groups all imports with the specified Prefix.
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      # Conflicts with govet check-shadowing
      - sloppyReassign
  goimports:
    local-prefixes: github.com/cheina97/timeserver
  govet:
    enable:
      - shadow
      - nilness
      - nilfunc
  misspell:
    locale: US
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: true # require an explanation for nolint directives
    require-specific: true # require nolint directives to be specific about which linter is being skipped
  dupl:
    threshold: 300
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    # - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errorlint
    # - err113
    - errcheck
    - errchkjson
    - errname
    - exhaustive
    # - exhaustruct
    - fatcontext
    # - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    # - gochecknoglobals
    # - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    # - godox
    - gofmt
    # - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    # - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    # - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    # - nlreturn
    - noctx
    - nolintlint
    # - nonamedreturns
    - nosprintfhostport
    # - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    # - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    # - wsl
    - zerologlint
issues:
  exclude-rules:
  - path: "_test.go"
    linters:
    - revive
