apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: ingress-nginx
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
  source:
    chart: ingress-nginx
    helm:
      valueFiles:
      - values.yaml
      values: |
        controller:
          watchIngressWithoutClass: true
          config:
            use-gzip: "true"
            gzip-types: "*"
          ingressClassResource:
            name: nginx
            enabled: true
            default: true
            controllerValue: "k8s.io/ingress-nginx"

    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.12.0