apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: metallb-system
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
  ignoreDifferences:
    - kind: CustomResourceDefinition
      group: apiextensions.k8s.io
      name: bgppeers.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
  sources:
  - repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: 0.14.9