apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- ingress.yml
- servicemonitor.yml

images:
- name: ghcr.io/netgroup-polito/cloudprog-2025/timeapi
  newTag: 09ce44be037203963e453a856b1f1ff714452687